influxdb:
    image: influxdb:latest
    ports:
        - 8086:8086
    environment:
        INFLUXDB_HTTP_AUTH_ENABLED: "true"
        INFLUXDB_DB: "iot"
        INFLUXDB_ADMIN_USER: "iotlnu"
        INFLUXDB_ADMIN_PASSWORD: "micropython"
        
    volumes:
        - ./data/influxdb:/var/lib/influxdb

grafana:
    image: grafana/grafana:latest
    ports: 
        - 3000:3000
    links:
        - "influxdb:influxdb"
    environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
        - ./data/grafana:/var/lib/grafana
    restart: always        

telegraf:
    image: telegraf:latest
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "iot"
    links:
        - "influxdb:influxdb"
    volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    privileged: true
